disabled_rules: # rule identifiers to exclude from running
  - colon
  - line_length
  - identifier_name
  - redundant_string_enum_value
opt_in_rules:
  - empty_count
included: # paths to include during linting. `--path` is ignored if present.
  - Tests
  - ../Moya-Pretty
excluded: # paths to ignore during linting. Takes precedence over `included`.  
  - Pods  
function_body_length:
  warning: 50