# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode11.5
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
    - gem install bundler:2.2.8
install:
    - bundle install
    - bundle exec pod repo update --silent
    - bundle exec pod install --project-directory=Example
script:
    - bundle exec fastlane scan --workspace Example/Moya-Pretty.xcworkspace
    - travis_wait 60 bundle exec pod lib lint --allow-warnings --fail-fast
deploy:
  provider: script
  script:
    - travis_wait 30 bundle exec pod trunk push --allow-warnings
  skip_cleanup: true
  on:
    tags: true
